name: Build and deploy to GitHub Pages

# run on pushes to your default branch
on:
  push:
    branches:
      - main
      - master

# grant explicit token permissions required for pushing / pages
permissions:
  contents: write    # allow pushing commits
  pages: write       # allow interacting with GitHub Pages (optional but recommended)
  id-token: write    # sometimes required for some actions

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # important so the job can push back using GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # branch to deploy to
          folder: dist              # folder to deploy
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}   # ensure the action uses the workflow token with write perms
